In [1]:
import pandas as pd

In [3]:
s = pd.Series([1,2,3,4])
s

0    1
1    2
2    3
3    4
dtype: int64

In [4]:
s = pd.Series([1,2,3,4], index = ['a','b','c','d'])
s

a    1
b    2
c    3
d    4
dtype: int64

In [8]:
data = [[   [1,444,'abc'],
            [2,555,'def'],
            [3,666,'ghi'],
            [4,444,'xyz']
]]
df = pd.DataFrame(data[0], columns=["Idx","Std_id","depart"])
df

   Idx  Std_id depart
0    1     444    abc
1    2     555    def
2    3     666    ghi
3    4     444    xyz

In [ ]:
display(df)

   Idx  Std_id depart
0    1     444    abc
1    2     555    def
2    3     666    ghi
3    4     444    xyz

In [10]:
df.dtypes

Idx       int64
Std_id    int64
depart      str
dtype: object

In [13]:
df.dtypes

Idx       int64
Std_id    int64
depart      str
dtype: object

In [18]:
df.head()

   Idx  Std_id depart
0    1     444    abc
1    2     555    def
2    3     666    ghi
3    4     444    xyz

In [21]:
df.describe()

            Idx      Std_id
count  4.000000    4.000000
mean   2.500000  527.250000
std    1.290994  106.274409
min    1.000000  444.000000
25%    1.750000  444.000000
50%    2.500000  499.500000
75%    3.250000  582.750000
max    4.000000  666.000000

In [24]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [25]:
df.columns

Index(['Idx', 'Std_id', 'depart'], dtype='str')

In [27]:
df['Std_id'].unique()
df['Std_id'].nunique()

3

In [ ]:
df['Std_id'].max()

np.int64(444)

In [ ]:
df['Std_id'].idxmin()

0

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Idx     4 non-null      int64
 1   Std_id  4 non-null      int64
 2   depart  4 non-null      str
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [35]:
d = df['depart'].value_counts()
d

depart
abc    1
def    1
ghi    1
xyz    1
Name: count, dtype: int64

In [36]:
df['Std_id'].sum()

np.int64(2109)

In [37]:
df.values

array([[1, 444, 'abc'],
       [2, 555, 'def'],
       [3, 666, 'ghi'],
       [4, 444, 'xyz']], dtype=object)

In [38]:
df = df.replace([1,666,"abc"],"fahd",inplace= True)
df

    Idx Std_id depart
0  fahd    444   fahd
1     2    555    def
2     3   fahd    ghi
3     4    444    xyz

In [42]:
df.Std_id = df.Std_id.map({444:"sdfsdf",555:"asdasdasd"})
df

    Idx     Std_id depart
0  fahd     sdfsdf    NaN
1     2  asdasdasd    NaN
2     3        NaN    NaN
3     4     sdfsdf    NaN

In [44]:
data = [[   [1,444,'abc'],
            [2,555,'def'],
            [3,666,'ghi'],
            [4,444,'xyz']
]]
df = pd.DataFrame(data[0], columns=["Idx","Std_id","depart"])
df

   Idx  Std_id depart
0    1     444    abc
1    2     555    def
2    3     666    ghi
3    4     444    xyz

In [48]:
df.depart.iloc[2]

'ghi'

In [51]:
df.iloc[:, 0:3]

   Idx  Std_id depart
0    1     444    abc
1    2     555    def
2    3     666    ghi
3    4     444    xyz